
cache: packages

sudo: true

matrix:
  include:
    - language: node_js
      node_js:
      - "8"

    - language: c++
      before_install: 
      - sudo apt-get update
      - sudo apt-get -y install build-essential python3 python3-dev python3-pip
      script: 
#      - python3 -m pip install numpy pandas --upgrade --ignore-installed
      - python3 -m pip install numpy pandas
      - cd src/python && make && make test

    - language: python
      python: 3.4
      script:
      - python3 -m pip install numpy pandas 
      - cd src/python && make PYVER=3.4 && make test

  allow_failures:
    - c++

#after_success:
#  - Rscript -e 'covr::codecov()'

warnings_are_errors: false

notifications:
  email:
    on_success: change
    on_failure: change

