dist: xenial

cache: packages

sudo: true

matrix:
  include:
    - language: node_js
      node_js:
      - "8"

    - name: native_cpp
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
      before_install: 
      - sudo apt-get update
      - sudo apt-get -y install build-essential python3 python3-dev python3-pip
      script: 
      - python3 -m pip install -U numpy pandas pybind11
      - make PYVER=3.5 
      - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
      - make PYVER=3.5 test

    - name: native_cpp_mpi
      before_install: 
      - sudo apt-get update
      - sudo apt-get -y install build-essential python3 python3-dev python3-pip mpich libmpich-dev
      script: 
      - python3 -m pip install -U numpy pandas pybind11
      - make PYVER=3.5 -f MPI.mk
      - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
      - make PYVER=3.5 -f MPI.mk test

    - name: cmake
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
      before_install: 
      - sudo apt-get update
      - sudo apt-get -y install build-essential python3 python3-dev python3-pip
      script:
      - python3 -m pip install -U numpy pandas pybind11
      - mkdir -p build
      - cd build
      - cmake .. -DPYVER=3.5
      - make

    # Prints out toolchain version info
    - name: travis_env
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
      before_install:
      - sudo apt-get update
      - sudo apt-get -y install build-essential python3 python3-dev python3-pip mpich libmpich-dev
      - python3 -m pip install -U numpy pandas pybind11
      script:
      - g++ --version
      - mpirun --version
      - python3 --version
      - python3 -c"import numpy;print(numpy.__version__)"
      - python3 -c"import pandas;print(pandas.__version__)"


    # - language: python
    #   python: 3.5
    #   script:
    #   - sudo apt install python3-dev 
    #   - python3 -m pip install -U numpy pandas 
    #   - make PYVER=3.5 test

    # - language: python
    #   python: 3.6
    #   script:
    #   - sudo apt install python3-dev 
    #   - python3 -m pip install -U numpy pandas 
    #   - make && make test

  allow_failures:
    - python: 3.5
    - python: 3.6

#after_success:
#  - Rscript -e 'covr::codecov()'

warnings_are_errors: false

notifications:
  email:
    on_success: change
    on_failure: change

