dist: xenial

cache: packages

sudo: true

matrix:
  include:
    # - language: node_js
    #   node_js:
    #   - "8"

    - name: native_cpp
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
      before_install: 
      - sudo apt-get update
      - sudo apt-get -y install build-essential python3 python3-dev python3-pip python3-virtualenv
      script:
      - virtualenv -p python3 .venv
      - source .venv/bin/activate
      - pip install -U numpy pandas pybind11
      - make && make test
      #- export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
      #- make test

    # - name: native_cpp_mpi
    #   before_install: 
    #   - sudo apt-get update
    #   - sudo apt-get -y install build-essential python3 python3-dev python3-pip mpich libmpich-dev
    #   script: 
    #   - python3 -m pip install -U numpy pandas pybind11
    #   - make -f MPI.mk
    #   - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
    #   - make -f MPI.mk test

    # - name: cmake
    #   addons:
    #     apt:
    #       sources:
    #       - ubuntu-toolchain-r-test
    #   before_install: 
    #   - sudo apt-get update
    #   - sudo apt-get -y install build-essential python3 python3-dev python3-pip
    #   script:
    #   - python3 -m pip install -U numpy pandas pybind11
    #   - mkdir -p build
    #   - cd build
    #   - cmake .. 
    #   - make

    # # Prints out toolchain version info
    # - name: travis_env
    #   addons:
    #     apt:
    #       sources:
    #       - ubuntu-toolchain-r-test
    #   before_install:
    #   - sudo apt-get update
    #   - sudo apt-get -y install build-essential python3 python3-dev python3-pip mpich libmpich-dev
    #   - python3 -m pip install -U numpy pandas pybind11
    #   script:
    #   - g++ --version
    #   - mpirun --version
    #   # bit pointless as not using venv?
    #   - python3 --version
    #   - python3 -c"import numpy;print(numpy.__version__)"
    #   - python3 -c"import pandas;print(pandas.__version__)"

    - language: python
      python: 3.5
      script:
      - pip install -U numpy pandas pybind11 
      - python setup.py build
      - python setup.py test

    - language: python
      python: 3.6
      before_install:
      - sudo apt-get update
      - sudo apt-get -y install build-essential mpich libmpich-dev
      install:
      - pip install pybind11 numpy pandas
      script:
      - python setup.py build
      - ./run_example.sh hello_world
      - ./run_example.sh diagnostics
      - python setup.py test

  allow_failures:
    - python: 3.5
    - python: 3.6

#after_success:
#  - Rscript -e 'covr::codecov()'

warnings_are_errors: false

notifications:
  email:
    on_success: change
    on_failure: change

