version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: install packages
          command: apt-get update && apt-get -y install build-essential python3 python3-dev python3-pip
      - run:
          name: Greeting
          command: g++ --version
      - run:
          name: python 
          command: python3 --version 
