version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      # - run:
      #     name: install packages
      #     command: sudo apt-get update && sudo apt-get -y install build-essential python3 python3-dev python3-pip libboost-python-dev libboost-numpy-dev
      - run:
          name: Greeting
          command: g++ -dumpversion.
      - run:
          name: python 
          command: python3 --version 
